### ISSUE TITLE
Practica #1 - RA y RV

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-ElvisS10#2]
[Practica1_Elvis.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-ElvisS10/files/6136299/Practica1_Elvis.pdf)

**Comment by AxayacatlS** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Esta bien y revisado
